### ISSUE TITLE
cannot access github page

### ISSUE THREAD

**Issue by pahans** [wso2/ux-font-wso2#106]
cannot access http://wso2-dev-ux.github.io/font-wso2/icons.html
![selection_087](https://user-images.githubusercontent.com/1552869/33269852-1ea9186a-d3a8-11e7-8bba-4a777646c38a.png)

**Comment by jeradrutnam** [comment]
Please use the new URL: http://wso2.github.io/ux-font-wso2/icons.html

We have move the repository to wso2 organization from wso2-dev-ux.

**Comment by pahans** [comment]
Fixed in https://github.com/wso2/ux-font-wso2/pull/107
